apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-access
  namespace: datadog
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: datadog
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader
  namespace: datadog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: api-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-node-status
rules:
- apiGroups: [""]
  resources: ["nodes", "services"]
  verbs: ["patch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grant-patch-node-status
subjects:
- kind: ServiceAccount
  name: api-access
  namespace: datadog
roleRef:
  kind: ClusterRole
  name: patch-node-status
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delete-kyverno-crd
rules:
- apiGroups: ["kyverno.io"]
  resources: ["clusterpolicies"]
  verbs: ["delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-kyverno-crd
subjects:
- kind: ServiceAccount
  name: api-access
  namespace: datadog
roleRef:
  kind: ClusterRole
  name: delete-kyverno-crd
  apiGroup: rbac.authorization.k8s.io


